import{a as b,S as w,i as l}from"./assets/vendor-CFFvTae-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const v="55520229-6b38dd18315a985816c1e4a23",M=b.create({baseURL:"https://pixabay.com/api/"});async function f(e,o){const a={key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await M.get("",{params:a})).data}const s={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")},S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function q(e){return`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>

      <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </li>
  `}function m(e){const o=e.map(q).join("");s.gallery.insertAdjacentHTML("beforeend",o),S.refresh()}function B(){s.gallery.innerHTML=""}function y(){s.loader.classList.remove("hidden")}function g(){s.loader.classList.add("hidden")}function P(){s.loadMoreBtn.classList.remove("hidden")}function u(){s.loadMoreBtn.classList.add("hidden")}const p=document.querySelector(".form"),E=document.querySelector(".load-more");let c,i,h;const D=15;p.addEventListener("submit",$);E.addEventListener("click",O);async function $(e){if(e.preventDefault(),c=new FormData(e.target).get("search-text").trim(),i=1,!c){l.error({title:"Error",message:"Please enter a search term!"});return}B(),y(),u();try{const a=await f(c,i),n=a.hits||[];if(!n.length){l.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}h=Math.ceil(a.totalHits/D),m(n),L()}catch{l.error({title:"Error",message:"Something went wrong. Try again later."})}finally{g()}p.reset()}async function O(){i+=1,u(),y();try{const e=await f(c,i);m(e.hits);const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"}),L()}catch(e){console.log(e.message)}finally{g()}}function L(){i<h?P():(u(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}
//# sourceMappingURL=index.js.map
